---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: skopeo-copy-disconnected-single-
  labels:
    tekton.dev/pipeline: skopeo-copy-disconnected-single
spec:
  params:
    - name: SOURCE_IMAGE_URL
      value: "docker://registry.redhat.io/ubi8/ubi-minimal:latest"
    - name: DESTINATION_IMAGE_URL
      value: "docker://harbor.f2775.sandbox999.opentlc.com/mirror/ubi-minimal:latest"
    - name: SRC_TLS_VERIFY
      value: "false"
    - name: DEST_TLS_VERIFY
      value: "true"
    - name: ARGS
      value: "--src-tls-verify=false --dest-tls-verify=true"

  pipelineRef:
    name: skopeo-copy-disconnected-single
  taskRunTemplate:
    serviceAccountName: pipeline
  timeouts:
    pipeline: 1h0m0s
  workspaces:
    - name: authsecret
      secret:
        secretName: combined-registry-auth
    - configMap:
        name: root-ca-certs
      name: root-ca-certs
    - configMap:
        name: mirror-registry-config
      name: registriesd
    - configMap:
        name: mirror-registry-config
      name: containerconfig