# This will build an image with all the needed things to use the OpenShift installer and client.
# There are also a few other goodies in here.

ARG TARGETPLATFORM

# For Arm64 you need to use CentOS Stream 9
#FROM registry.access.redhat.com/ubi9/ubi:9.5-1736404036
FROM quay.io/centos/centos:stream9

USER 0

# Update system packages and install needed tools via dnf and pip
RUN dnf update -y \
 && dnf copr enable nmstate/nmstate-git -y \
 && dnf install -y git wget nmstate tar jq python3-pip python3-wheel python3-devel nano \
 && python3 -m pip install ansible jmespath nmstate \
 && ansible-galaxy collection install community.general \
 && ansible-galaxy collection install community.crypto \
 && dnf clean all \
 && rm -rf /var/cache/yum

# Install OpenShift binaries - some have multi-arch support, some do not
RUN if [ "$TARGETPLATFORM" = "linux/amd64" ]; then OS=linux && ARCH=x86_64 && IARCH=amd64 && OI=openshift-install-linux && OC=openshift-client-linux; elif [ "$TARGETPLATFORM" = "linux/arm64" ]; then OS=linux && ARCH=arm64 && IARCH=aarch64 && OI=openshift-install-linux-arm64 && OC=openshift-client-linux-arm64; else OS=linux ARCH=x86_64 && IARCH=amd64 && echo "${TARGETPLATFORM} - Building for ARCH: $ARCH | IARCH: $IARCH | OS: $OS not supported" && exit 1; fi \
 && echo "${TARGETPLATFORM} - Building for ARCH: $ARCH | IARCH: $IARCH | OS: $OS" \
 && mkdir -p /tmp/bintmp \
 && cd /tmp/bintmp \
 && wget https://mirror.openshift.com/pub/openshift-v4/clients/butane/latest/butane-${IARCH} \
 && wget https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/${OI}.tar.gz \
 && wget https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/${OC}.tar.gz \
 && if [ "$ARCH" = "x86_64" ]; then \
    wget https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/oc-mirror.rhel9.tar.gz \
 && wget https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/opm-linux-rhel9.tar.gz \
 && wget https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/ccoctl-linux.tar.gz \
 && mv opm-rhel9 opm \
 fi \
 && tar zxvf *.tar.gz \
 && mv butane-amd64 butane \
 && chmod a+x oc kubectl openshift-install butane \
 && mv oc kubectl openshift-install butane /usr/local/bin/ \
 && if [ "$ARCH" = "x86_64" ]; then chmod a+x oc-mirror opm ccoctl && mv oc-mirror opm ccoctl /usr/local/bin/; fi \
 && cd / \
 && rm -rf /tmp/bintmp

# Install other optional tools such as Helm, Kustomize, etc.
RUN curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash \
 && curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash \
 && mv kustomize /usr/local/bin/

WORKDIR /data