# This will build an image with all the needed things to use the OpenShift installer and client.
# There are also a few other goodies in here.

ARG TARGETPLATFORM

# For Arm64 you need to use CentOS Stream
#FROM registry.access.redhat.com/ubi9/ubi:9.5-1736404036
FROM quay.io/centos/centos:stream9

USER 0

# Update system packages and install needed tools via dnf and pip
#&& dnf copr enable nmstate/nmstate-git -y \
RUN dnf update -y \
 && dnf clean all \
 && rm -rf /var/cache/yum

RUN dnf install -y git wget nmstate tar jq python3-pip python3-pip-wheel python3-devel nano python3-gobject bash-completion \
 && dnf clean all \
 && rm -rf /var/cache/yum

# If you're managing much more than this, you should probably use an EE version of the image
RUN python3 -m pip install ansible jmespath nmstate \
 && ansible-galaxy collection install community.general \
 && ansible-galaxy collection install community.crypto

# Download various OpenShift binaries
COPY download-ocp-binaries.sh /tmp/download-ocp-binaries.sh
RUN DEST_MODE="system" /tmp/download-ocp-binaries.sh \
 && rm -f /tmp/download-ocp-binaries.sh

# Install other optional tools such as Helm, Kustomize, etc.
RUN curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash \
 && curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash \
 && mv kustomize /usr/local/bin/

WORKDIR /data