# This image builds upon the binaries image
ARG C_BASE_IMAGE=quay.io/kenmoini/ocp-install-utils:latest
FROM $C_BASE_IMAGE

COPY mirror-release.sh /mirror-release.sh
COPY oc-mirror.sh /oc-mirror.sh
COPY entrypoint.sh /entrypoint.sh

#CMD ["/mirror-release.sh"]
ENTRYPOINT ["/entrypoint.sh"]