# This image builds upon the binaries image
FROM quay.io/kenmoini/ocp-install-utils:latest

COPY mirror-release.sh /mirror-release.sh
COPY entrypoint.sh /entrypoint.sh

#CMD ["/mirror-release.sh"]
ENTRYPOINT ["/entrypoint.sh"]