name: Binaries - Build OCP FIPS Install Tools Container
on:
  push:
    branches:
      - main
    paths:
      - binaries/Containerfile.fips
      - .github/workflows/binaries-build-fips-container.yml

  # Schedule workflow run at 00:00 on Sunday
  schedule:
    - cron: '0 2 * * 0'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build the container
  build-container:
    name: Build Container
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:

    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      #with:
      #  platforms: arm64,amd64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        # list of Docker images to use as base name for tags
        images: |
          quay.io/kenmoini/ocp-install-utils
        # generate Docker tags based on the following events/attributes
        tags: |
          type=schedule
          type=ref,event=branch,suffix=-fips
          type=ref,event=tag,suffix=-fips
          type=sha,prefix=,suffix=-fips,format=short
          type=sha,prefix=,suffix=-fips,format=long
          type=raw,value=latest-fips

    - name: Login to Quay Container Registry
      uses: docker/login-action@v3
      with:
        registry: quay.io
        username: "${{ secrets.REGISTRY_USERNAME }}"
        password: "${{ secrets.REGISTRY_TOKEN }}"

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: binaries/Containerfile.fips
        labels: ${{ steps.meta.outputs.labels }}
        tags: ${{ steps.meta.outputs.tags }}
        push: true
        provenance: false
        #platforms: linux/amd64, linux/arm64
        #provenance: mode=max
        #sbom: true
        #cache-from: type=gha
        #cache-to: type=gha,mode=max